//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gorgias.Manual
{
    using System;
    using System.Collections.Generic;
    
    public partial class Album
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Album()
        {
            this.Contents = new HashSet<Content>();
        }
    
        public int AlbumID { get; set; }
        public string AlbumName { get; set; }
        public System.DateTime AlbumDateCreated { get; set; }
        public bool AlbumStatus { get; set; }
        public string AlbumCover { get; set; }
        public bool AlbumIsDeleted { get; set; }
        public int CategoryID { get; set; }
        public int ProfileID { get; set; }
        public int AlbumView { get; set; }
        public System.DateTime AlbumDatePublish { get; set; }
        public System.DateTime AlbumDateExpire { get; set; }
        public int AlbumAvailability { get; set; }
        public Nullable<bool> AlbumHasComment { get; set; }
        public string AlbumReadingLanguageCode { get; set; }
        public Nullable<int> AlbumRepostValue { get; set; }
        public Nullable<int> AlbumRepostRequest { get; set; }
        public Nullable<int> AlbumRepostAttempt { get; set; }
        public Nullable<decimal> AlbumPrice { get; set; }
        public Nullable<bool> AlbumIsTokenAvailable { get; set; }
        public Nullable<int> AlbumPriceToken { get; set; }
        public Nullable<int> ContentRatingID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Content> Contents { get; set; }
    }
}
