//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gorgias.Manual
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public City()
        {
            this.CityChilds = new HashSet<City>();
        }
    
        public int CityID { get; set; }
        public string CityName { get; set; }
        public bool CityStatus { get; set; }
        public int CountryID { get; set; }
        public byte[] CityUpdateDate { get; set; }
        public string CityLanguageCode { get; set; }
        public Nullable<int> CityParentID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<City> CityChilds { get; set; }
        public virtual City City2 { get; set; }
        public virtual Country Country { get; set; }
    }
}
