//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gorgias.Manual
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Profile()
        {
            this.Albums = new HashSet<Album>();
            this.Categories = new HashSet<Category>();
        }
    
        public int ProfileID { get; set; }
        public string ProfileFullname { get; set; }
        public string ProfileFullnameEnglish { get; set; }
        public bool ProfileIsPeople { get; set; }
        public bool ProfileIsDeleted { get; set; }
        public System.DateTime ProfileDateCreated { get; set; }
        public string ProfileDescription { get; set; }
        public long ProfileView { get; set; }
        public int ProfileLike { get; set; }
        public int ProfileCredit { get; set; }
        public string ProfileURL { get; set; }
        public string ProfileShortDescription { get; set; }
        public string ProfileImage { get; set; }
        public string ProfileEmail { get; set; }
        public bool ProfileStatus { get; set; }
        public bool ProfileIsConfirmed { get; set; }
        public int ProfileTypeID { get; set; }
        public int ThemeID { get; set; }
        public int SubscriptionTypeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Album> Albums { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Category> Categories { get; set; }
    }
}
