//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gorgias
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attribute
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Attribute()
        {
            this.ProfileAttributes = new HashSet<ProfileAttribute>();
        }
    
        public int AttributeID { get; set; }
        public string AttributeName { get; set; }
        public string AttributeCaption { get; set; }
        public bool AttributeStatus { get; set; }
        public int AttributeMode { get; set; }
        public string AttributeRule { get; set; }
        public string AttributeType { get; set; }
        public string AttributeImage { get; set; }
        public string AttributeDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfileAttribute> ProfileAttributes { get; set; }
    }
}
