//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gorgias
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int CommentID { get; set; }
        public string CommentNote { get; set; }
        public int CommentLike { get; set; }
        public System.DateTime CommentDateTime { get; set; }
        public bool CommentStatus { get; set; }
        public int ProfileID { get; set; }
        public int ContentID { get; set; }
    
        public virtual Content Content { get; set; }
        public virtual Profile Profile { get; set; }
    }
}
