//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gorgias
{
    using System;
    using System.Collections.Generic;
    
    public partial class Connection
    {
        public int ProfileID { get; set; }
        public int RequestedProfileID { get; set; }
        public int RequestTypeID { get; set; }
        public bool ConnectStatus { get; set; }
        public System.DateTime ConnectDateCreated { get; set; }
    
        public virtual Profile Profile { get; set; }
        public virtual Profile Profile1 { get; set; }
        public virtual RequestType RequestType { get; set; }
    }
}
