//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gorgias
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContentType()
        {
            this.Contents = new HashSet<Content>();
            this.ContentTypeChilds = new HashSet<ContentType>();
        }
    
        public int ContentTypeID { get; set; }
        public string ContentTypeName { get; set; }
        public int ContentTypeOrder { get; set; }
        public bool ContentTypeStatus { get; set; }
        public string ContentTypeLanguageCode { get; set; }
        public string ContentTypeExpression { get; set; }
        public Nullable<int> ContentTypeParentID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Content> Contents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContentType> ContentTypeChilds { get; set; }
        public virtual ContentType ContentTypeParent { get; set; }
    }
}
