//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gorgias
{
    using System;
    using System.Collections.Generic;
    
    public partial class Newsletter
    {
        public int NewsletterID { get; set; }
        public string NewsletterName { get; set; }
        public string NewsletterNote { get; set; }
        public bool NewsletterStatus { get; set; }
    }
}
