//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gorgias
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int PaymentID { get; set; }
        public System.DateTime PaymentDateCreated { get; set; }
        public Nullable<System.DateTime> PaymentDatePaid { get; set; }
        public bool PaymentIsPaid { get; set; }
        public double PaymentAmount { get; set; }
        public string PaymentNote { get; set; }
        public int ProfileCommissionID { get; set; }
    
        public virtual ProfileCommission ProfileCommission { get; set; }
    }
}
