//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gorgias
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfileSetting
    {
        public int ProfileID { get; set; }
        public string ProfileLanguageApp { get; set; }
        public Nullable<int> ProfileCityID { get; set; }
        public Nullable<System.DateTime> ProfileBirthday { get; set; }
    
        public virtual Profile Profile { get; set; }
    }
}
