//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gorgias
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfileReport
    {
        public int ProfileReportID { get; set; }
        public int ProfileReportActivityCount { get; set; }
        public double ProfileReportRevenue { get; set; }
        public int ReportTypeID { get; set; }
        public int ProfileID { get; set; }
        public int RevenueID { get; set; }
    
        public virtual Profile Profile { get; set; }
        public virtual ReportType ReportType { get; set; }
        public virtual Revenue Revenue { get; set; }
    }
}
