//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gorgias
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfileType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProfileType()
        {
            this.Profiles = new HashSet<Profile>();
            this.ProfileTypeChilds = new HashSet<ProfileType>();
        }
    
        public int ProfileTypeID { get; set; }
        public string ProfileTypeName { get; set; }
        public bool ProfileTypeStatus { get; set; }
        public string ProfileTypeImage { get; set; }
        public string ProfileTypeDescription { get; set; }
        public Nullable<int> ProfileTypeParentID { get; set; }
        public string ProfileTypeLanguageCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Profile> Profiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfileType> ProfileTypeChilds { get; set; }
        public virtual ProfileType ProfileTypeParent { get; set; }
    }
}
