//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gorgias
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfileActivity
    {
        public int ProfileID { get; set; }
        public int AlbumID { get; set; }
        public int ActivityTypeID { get; set; }
        public int ProfileActivityCount { get; set; }
        public System.DateTime ProfileActivityDateTime { get; set; }
    
        public virtual ActivityType ActivityType { get; set; }
        public virtual Album Album { get; set; }
        public virtual Profile Profile { get; set; }
    }
}
