//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gorgias
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quote
    {
        public int QuoteID { get; set; }
        public string QuoteName { get; set; }
        public bool QuoteStatus { get; set; }
        public string QuoteLanguageCode { get; set; }
        public int QuoteProbability { get; set; }
        public int CategoryID { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
