//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gorgias
{
    using System;
    using System.Collections.Generic;
    
    public partial class Share
    {
        public int ProfileActivityID { get; set; }
        public string ProfileActivityShare { get; set; }
    
        public virtual ProfileActivity ProfileActivity { get; set; }
    }
}
