//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gorgias
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocialNetwork
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SocialNetwork()
        {
            this.ProfileSocialNetworks = new HashSet<ProfileSocialNetwork>();
        }
    
        public int SocialNetworkID { get; set; }
        public string SocialNetworkName { get; set; }
        public bool SocialNetworkStatus { get; set; }
        public string SocialNetworkURL { get; set; }
        public string SocialNetworkImage { get; set; }
        public string SocialNetworkDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfileSocialNetwork> ProfileSocialNetworks { get; set; }
    }
}
