//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gorgias
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.UserProfiles = new HashSet<UserProfile>();
        }
    
        public int UserID { get; set; }
        public string UserFullname { get; set; }
        public string UserEmail { get; set; }
        public bool UserStatus { get; set; }
        public bool UserIsBlocked { get; set; }
        public System.DateTime UserDateCreated { get; set; }
        public System.DateTime UserDateConfirmed { get; set; }
        public Nullable<int> CountryID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserProfile> UserProfiles { get; set; }
        public virtual Country Country { get; set; }
    }
}
